/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jacobijni_lib_JacobiCalculator */

#ifndef _Included_jacobijni_lib_JacobiCalculator
#define _Included_jacobijni_lib_JacobiCalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jacobijni_lib_JacobiCalculator
 * Method:    calcjacobi
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_jacobijni_lib_JacobiCalculator_calcjacobi
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
